/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppJellyfinRouteImport } from './routes/_app/jellyfin'
import { Route as AppUpdatesRouteImport } from './routes/_app/updates'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppJellyfinRoute = AppJellyfinRouteImport.update({
  id: '/jellyfin',
  path: '/jellyfin',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/health': typeof AppHealthRoute
  '/jellyfin': typeof AppJellyfinRoute
  '/updates': typeof AppUpdatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/health': typeof AppHealthRoute
  '/jellyfin': typeof AppJellyfinRoute
  '/updates': typeof AppUpdatesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/jellyfin': typeof AppJellyfinRoute
  '/_app/updates': typeof AppUpdatesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/health' | '/jellyfin' | '/updates'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/health' | '/jellyfin' | '/updates' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/health'
    | '/_app/jellyfin'
    | '/_app/updates'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jellyfin': {
      id: '/_app/jellyfin'
      path: '/jellyfin'
      fullPath: '/jellyfin'
      preLoaderRoute: typeof AppJellyfinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHealthRoute: typeof AppHealthRoute
  AppJellyfinRoute: typeof AppJellyfinRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHealthRoute: AppHealthRoute,
  AppJellyfinRoute: AppJellyfinRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
