/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBackupsRouteImport } from './routes/_app/backups'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppJellyfinRouteImport } from './routes/_app/jellyfin'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppTailscaleRouteImport } from './routes/_app/tailscale'
import { Route as AppUpdatesRouteImport } from './routes/_app/updates'
import { Route as AppConsoleVmidRouteImport } from './routes/_app/console/$vmid'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppJellyfinRoute = AppJellyfinRouteImport.update({
  id: '/jellyfin',
  path: '/jellyfin',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTailscaleRoute = AppTailscaleRouteImport.update({
  id: '/tailscale',
  path: '/tailscale',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleVmidRoute = AppConsoleVmidRouteImport.update({
  id: '/console/$vmid',
  path: '/console/$vmid',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/backups': typeof AppBackupsRoute
  '/health': typeof AppHealthRoute
  '/jellyfin': typeof AppJellyfinRoute
  '/logs': typeof AppLogsRoute
  '/tailscale': typeof AppTailscaleRoute
  '/updates': typeof AppUpdatesRoute
  '/console/$vmid': typeof AppConsoleVmidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backups': typeof AppBackupsRoute
  '/health': typeof AppHealthRoute
  '/jellyfin': typeof AppJellyfinRoute
  '/logs': typeof AppLogsRoute
  '/tailscale': typeof AppTailscaleRoute
  '/updates': typeof AppUpdatesRoute
  '/': typeof AppIndexRoute
  '/console/$vmid': typeof AppConsoleVmidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/backups': typeof AppBackupsRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/jellyfin': typeof AppJellyfinRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/tailscale': typeof AppTailscaleRoute
  '/_app/updates': typeof AppUpdatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/console/$vmid': typeof AppConsoleVmidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backups'
    | '/health'
    | '/jellyfin'
    | '/logs'
    | '/tailscale'
    | '/updates'
    | '/console/$vmid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backups'
    | '/health'
    | '/jellyfin'
    | '/logs'
    | '/tailscale'
    | '/updates'
    | '/'
    | '/console/$vmid'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/backups'
    | '/_app/health'
    | '/_app/jellyfin'
    | '/_app/logs'
    | '/_app/tailscale'
    | '/_app/updates'
    | '/_app/'
    | '/_app/console/$vmid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jellyfin': {
      id: '/_app/jellyfin'
      path: '/jellyfin'
      fullPath: '/jellyfin'
      preLoaderRoute: typeof AppJellyfinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tailscale': {
      id: '/_app/tailscale'
      path: '/tailscale'
      fullPath: '/tailscale'
      preLoaderRoute: typeof AppTailscaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/console/$vmid': {
      id: '/_app/console/$vmid'
      path: '/console/$vmid'
      fullPath: '/console/$vmid'
      preLoaderRoute: typeof AppConsoleVmidRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBackupsRoute: typeof AppBackupsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppJellyfinRoute: typeof AppJellyfinRoute
  AppLogsRoute: typeof AppLogsRoute
  AppTailscaleRoute: typeof AppTailscaleRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConsoleVmidRoute: typeof AppConsoleVmidRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupsRoute: AppBackupsRoute,
  AppHealthRoute: AppHealthRoute,
  AppJellyfinRoute: AppJellyfinRoute,
  AppLogsRoute: AppLogsRoute,
  AppTailscaleRoute: AppTailscaleRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppConsoleVmidRoute: AppConsoleVmidRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
